import assert from "node:assert/strict";
import { foundation, expansion, migration, login, scalar } from "./helpers/database.js";
import { resolveTenantHostname } from "../src/utils/tenant.js";
import { mapDatabaseRow } from "../src/services/academicDataService.js";

const db = await foundation();
const owner = "00000000-0000-4000-8000-000000000001";
const teacher = "00000000-0000-4000-8000-000000000002";
const outsider = "00000000-0000-4000-8000-000000000003";
async function add(table, data) {
  const keys = Object.keys(data);
  return scalar(db, `insert into public.${table}(${keys.join(",")}) values(${keys.map((_, i) => `$${i + 1}`).join(",")}) returning id`, Object.values(data));
}
async function rejects(sql, params = []) { await assert.rejects(() => db.query(sql, params)); }
try {
  await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'owner@example.test',now()),($2,'teacher@example.test',now()),($3,'other@example.test',now())", [owner, teacher, outsider]);
  const schoolId = await add("schools", { name: "Existing school", slug: "existing-school" });
  const otherSchool = await add("schools", { name: "Other school", slug: "other-school" });
  await db.query("insert into public.school_memberships(school_id,user_id,role) values($1,$2,'school_admin'),($1,$3,'subject_teacher'),($4,$5,'school_admin')", [schoolId, owner, teacher, otherSchool, outsider]);
  const classId = await add("school_classes", { school_id: schoolId, name: "Year 1" });
  const subjectId = await add("school_subjects", { school_id: schoolId, name: "Mathematics" });
  const assignmentId = await add("teacher_assignments", { school_id: schoolId, user_id: teacher, role: "subject_teacher", class_id: classId, subject_id: subjectId });
  for (const file of expansion) await migration(db, file);
  assert.equal(await scalar(db, "select count(*)::integer from public.teacher_assignments where id=$1 and teacher_id is not null", [assignmentId]), 1);
  assert.equal(await scalar(db, "select count(*)::integer from public.profiles"), 3);
  const sessionId = await add("academic_sessions", { school_id: schoolId, name: "2026/27", starts_on: "2026-09-01", ends_on: "2027-07-31" });
  const offlineTeacher = await add("teachers", { school_id: schoolId, display_name: "Offline teacher" });
  await login(db, owner);
  await db.query("select public.assign_teacher_entity($1,$2,'class_teacher',$3,null,$4)", [schoolId, offlineTeacher, classId, sessionId]);
  assert.equal(await scalar(db, "select count(*)::integer from public.teacher_assignments where teacher_id=$1 and user_id is null", [offlineTeacher]), 1);
  await rejects("insert into public.school_classes(school_id,name,section_id) values($1,'Invalid',$2)", [otherSchool, classId]);
  await db.exec("reset role");
  const otherSection = await add("school_sections", { school_id: otherSchool, name: "Other section" });
  await rejects("insert into public.school_classes(school_id,name,section_id) values($1,'Cross tenant',$2)", [schoolId, otherSection]);
  await login(db, owner);
  await db.query("select public.link_teacher_account($1,$2,'other@example.test')", [schoolId, offlineTeacher]);
  await login(db, outsider);
  assert.equal(await scalar(db, "select count(*)::integer from public.student_enrollments"), 0);
  await db.exec("reset role");
  const invalidScheme = await add("assessment_schemes", { school_id: schoolId, name: "Invalid weights" });
  await rejects("update public.assessment_schemes set status='active' where id=$1", [invalidScheme]);
  const invalidScale = await add("grading_scales", { school_id: schoolId, name: "Incomplete bands" });
  await add("grading_scale_items", { school_id: schoolId, scale_id: invalidScale, minimum_score: 40, maximum_score: 100, grade: "Pass" });
  await rejects("update public.grading_scales set status='active' where id=$1", [invalidScale]);
  const termId = await add("academic_terms", { school_id: schoolId, session_id: sessionId, name: "First term", sort_order: 1 });
  const schemeId = await add("assessment_schemes", { school_id: schoolId, name: "School scheme" });
  const componentId = await add("assessment_components", { school_id: schoolId, scheme_id: schemeId, name: "Assessment", max_score: 20, weight: 100, sort_order: 1 });
  await db.query("update public.assessment_schemes set status='active' where id=$1", [schemeId]);
  await rejects("update public.assessment_components set max_score=30 where id=$1", [componentId]);
  const scaleId = await add("grading_scales", { school_id: schoolId, name: "Grades" });
  await add("grading_scale_items", { school_id: schoolId, scale_id: scaleId, minimum_score: 0, maximum_score: 70, grade: "B", remark: "Good" });
  await add("grading_scale_items", { school_id: schoolId, scale_id: scaleId, minimum_score: 70, maximum_score: 100, grade: "A", remark: "Excellent" });
  await db.query("update public.grading_scales set status='active' where id=$1", [scaleId]);
  const studentId = await add("students", { school_id: schoolId, admission_number: "001", first_name: "Ada", last_name: "Test", class_id: classId });
  const enrollmentId = await add("student_enrollments", { school_id: schoolId, student_id: studentId, class_id: classId, session_id: sessionId });
  const futureSessionId = await add("academic_sessions", { school_id: schoolId, name: "2027/28", starts_on: "2027-09-01", ends_on: "2028-07-31" });
  await add("student_enrollments", { school_id: schoolId, student_id: studentId, class_id: classId, session_id: futureSessionId });
  await login(db, outsider);
  assert.equal(await scalar(db, "select count(*)::integer from public.student_enrollments where school_id=$1", [schoolId]), 1);
  await db.exec("reset role");
  const offeringId = await add("subject_offerings", { school_id: schoolId, class_id: classId, session_id: sessionId, subject_id: subjectId, assessment_scheme_id: schemeId, grading_scale_id: scaleId });
  const batchId = await add("result_batches", { school_id: schoolId, offering_id: offeringId, class_id: classId, session_id: sessionId, term_id: termId, assessment_scheme_id: schemeId, grading_scale_id: scaleId });
  const templateId = await add("result_templates", { school_id: schoolId, name: "Classic" });
  await db.query("update public.result_templates set status='active' where id=$1", [templateId]);
  const resultId = await add("student_results", { school_id: schoolId, enrollment_id: enrollmentId, class_id: classId, session_id: sessionId, term_id: termId, template_id: templateId });
  const academicId = await add("academic_results", { school_id: schoolId, student_result_id: resultId, batch_id: batchId, class_id: classId, session_id: sessionId, term_id: termId, assessment_scheme_id: schemeId });
  await login(db, teacher);
  await rejects("insert into public.assessment_scores(school_id,academic_result_id,assessment_scheme_id,component_id,score) values($1,$2,$3,$4,21)", [schoolId, academicId, schemeId, componentId]);
  await db.query("insert into public.assessment_scores(school_id,academic_result_id,assessment_scheme_id,component_id,score) values($1,$2,$3,$4,16)", [schoolId, academicId, schemeId, componentId]);
  const calculated = (await db.query("select * from public.calculate_academic_result($1)", [academicId])).rows[0];
  assert.equal(Number(calculated.total), 80); assert.equal(calculated.grade, "A");
  await rejects("select published_snapshot from public.student_results");
  await rejects("select public.get_published_report($1)", [resultId]);
  await rejects("select public.transition_result_batch($1,'published')", [batchId]);
  await db.query("select public.transition_result_batch($1,'submitted')", [batchId]);
  await login(db, outsider);
  assert.equal(await scalar(db, "select count(*)::integer from public.students"), 1);
  assert.equal(await scalar(db, "select count(*)::integer from public.assessment_scores"), 1);
  // Class teachers may read their class, but cannot edit subject scores.
  assert.equal((await db.query("update public.assessment_scores set score=1 where academic_result_id=$1 returning id", [academicId])).rows.length, 0);
  await rejects("select public.transition_result_batch($1,'under_review')", [batchId]);
  await login(db, owner);
  for (const status of ["under_review", "approved", "published"]) await db.query("select public.transition_result_batch($1,$2)", [batchId, status]);
  for (const status of ["submitted", "under_review", "approved", "published"]) await db.query("select public.transition_student_result($1,$2)", [resultId, status]);
  const snapshot = await scalar(db, "select public.get_published_report($1)", [resultId]);
  assert.equal(snapshot.academics[0].calculation.grade, "A");
  assert.equal(await scalar(db, "select count(*)::integer from public.result_verifications"), 1);
  await login(db, teacher);
  await rejects("select public.get_published_report($1)", [resultId]);
  await login(db, outsider);
  assert.equal((await scalar(db, "select public.get_published_report($1)", [resultId])).academics[0].calculation.grade, "A");
  await login(db, owner);
  await db.query("select public.revoke_result_verification($1,'Corrected version pending')", [resultId]);
  assert.equal(await scalar(db, "select status from public.result_verifications"), "revoked");
  await db.exec("reset role");
  const correctedId = await add("student_results", { school_id: schoolId, enrollment_id: enrollmentId, class_id: classId, session_id: sessionId, term_id: termId, template_id: templateId, version: 2, supersedes_id: resultId });
  assert.notEqual(correctedId, resultId);
  await rejects("insert into public.student_results(school_id,enrollment_id,class_id,session_id,term_id,version) values($1,$2,$3,$4,$5,3)", [schoolId, enrollmentId, classId, sessionId, termId]);
  await rejects("delete from public.assessment_scores where academic_result_id=$1", [academicId]);
  await rejects("update public.student_results set published_snapshot='{}' where id=$1", [resultId]);
  await rejects("delete from public.audit_logs");
  const planId = await scalar(db, "select id from public.subscription_plans where code='standard' and unit_price=100 and recommended");
  const subscriptionId = await add("school_subscriptions", { school_id: schoolId, plan_id: planId, status: "active", starts_at: "2026-01-01", ends_at: "2099-01-01" });
  const periodId = await add("subscription_periods", { school_id: schoolId, subscription_id: subscriptionId, starts_on: "2026-09-01", ends_on: "2026-12-31", pricing_type: "per_student_per_term", currency: "NGN", student_count: 500, unit_price: 100, plan_snapshot: { name: "Standard", unitPrice: 100 } });
  assert.equal(Number(await scalar(db, "select amount_due from public.subscription_periods where id=$1", [periodId])), 50000);
  await db.query("update public.subscription_plans set unit_price=120 where id=$1", [planId]);
  assert.equal(Number(await scalar(db, "select amount_due from public.subscription_periods where id=$1", [periodId])), 50000);
  await rejects("update public.subscription_periods set student_count=1 where id=$1", [periodId]);
  await login(db, teacher);
  assert.equal(await scalar(db, "select count(*)::integer from public.subscription_periods"), 0);
  assert.equal((await scalar(db, "select public.get_school_entitlements($1)", [schoolId])).result_management, true);
  await rejects("select public.get_school_entitlements($1)", [otherSchool]);
  await rejects("insert into public.payments(school_id,period_id,amount,currency,status,paid_at) values($1,$2,50000,'NGN','succeeded',now())", [schoolId, periodId]);
  await login(db, "", "anon");
  assert.equal(await scalar(db, "select count(*)::integer from public.subscription_plans"), 3);
  await rejects("select * from public.result_verifications");
  await rejects("select * from public.students");
  await db.exec("reset role");
  await db.query("insert into private.platform_admins(user_id) values($1)", [owner]);
  await login(db, owner);
  await db.query("update public.subscription_plans set status='inactive' where id=$1", [planId]);
  assert.equal(await scalar(db, "select count(*)::integer from public.subscription_plans"), 3);
  await db.query("update public.subscription_plans set status='active' where id=$1", [planId]);
  await db.query("select public.platform_remove_school($1)", [schoolId]);
  assert.equal(await scalar(db, "select status from public.schools where id=$1", [schoolId]), "suspended");
  await rejects("select public.platform_set_school_status($1,'active')", [schoolId]);
  await login(db, teacher);
  assert.equal(await scalar(db, "select count(*)::integer from public.assessment_scores"), 0);
  await db.exec("reset role");
  assert.equal(await scalar(db, "select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity"), 0);
  assert.equal(await scalar(db, "select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and has_function_privilege('anon',p.oid,'execute')"), 0);
  assert.equal(await scalar(db, "select count(*)::integer from information_schema.columns where table_schema='public' and column_name='school_id' and is_nullable='YES'"), 0);
  assert.deepEqual(resolveTenantHostname("goshen.resultmaker.com:5173"), { schoolSlug: "goshen", development: false });
  assert.equal(resolveTenantHostname("localhost:5173").schoolSlug, null);
  assert.equal(resolveTenantHostname("goshen.resultmaker.com.evil.test").schoolSlug, null);
  assert.deepEqual(mapDatabaseRow({ school_id: "a", custom_fields: { school_id: "keep" } }), { schoolId: "a", customFields: { school_id: "keep" } });
  console.log("PASS expansion: backfill, RLS, scores, publication, immutable history, billing and frontend adapters");
} finally { await db.close(); }
