import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const tabs=await fetch('http://127.0.0.1:9222/json').then(r=>r.json());const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];ws.addEventListener('message',({data})=>{const m=JSON.parse(data);if(m.id){pending.get(m.id)?.(m.result);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});const send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
async function wait(expression){for(let n=0;n<100;n++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);}
try{
await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:'http://localhost:5173/'});await wait("document.querySelectorAll('.plan-card').length===3");
for(const width of [1440,768,390]){await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<500});await new Promise(r=>setTimeout(r,150));assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);assert.equal(await evaluate("[...document.querySelectorAll('.plan-card,.home-feature-grid>.card')].every(e=>parseFloat(getComputedStyle(e).padding)>=24)"),true);const tops=JSON.parse(await evaluate("JSON.stringify([...document.querySelectorAll('.plan-card')].map(e=>e.getBoundingClientRect().top))"));assert.equal(new Set(tops).size,width>760?1:3);for(const theme of ['light','dark']){await evaluate(`import('/src/app/theme.js').then(m=>m.applyTheme('${theme}'))`);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(`.browser-check/home-${theme}-${width}.png`,Buffer.from(shot.data,'base64'));}}
await evaluate("document.querySelector('[data-action=signup-modal]').click()");await wait("!!document.querySelector('#signup-form')");assert.equal(await evaluate("!!document.querySelector('#signup-school') && !document.querySelector('#signup-kind') && !document.querySelector('#signup-slug')"),true);await evaluate("document.querySelector('.password-toggle').click()");assert.equal(await evaluate("document.querySelector('#signup-password').type"),'text');await evaluate("document.querySelector('.modal-close').click();document.querySelector('.footer-grid a[href=\"/#faqs\"]').click()");await wait("location.hash==='#faqs' && document.querySelector('#faqs').getBoundingClientRect().top<innerHeight");await evaluate("import('/src/app/router.js').then(m=>m.navigate('/pricing'))");await wait("document.querySelectorAll('.plan-card').length===3");assert.equal(await evaluate("document.querySelector('.recommended').textContent.includes('Standard')"),true);assert.deepEqual(errors,[]);console.log('PASS: desktop/tablet/mobile cards, both themes, signup, password visibility, FAQ navigation, pricing and no runtime exceptions. No accounts created.');
}finally{ws.close();}
