import { initializeTheme } from "./app/theme.js";
import "./styles/variables.css";
import "./styles/layout.css";
import "./styles/components.css";
import "./styles/responsive.css";
import "./styles/brand-and-reports.css";
import "./styles/public-site.css";
import "./styles/main.css";
import "./styles/academic.css";
import "./styles/themes.css";
import { startApp } from "./app/app.js";
initializeTheme();
startApp();
